# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: fuel-stackurity-theme-deployment-puppet
  type: shell
  role: [fuel-stackurity-theme_role]
  version: 2.0.0
  role: [primary-controller, controller]
  required_for: [post_deployment_end]
  requires: [post_deployment_start,horizon]
  parameters:
    cmd: bash deploy.sh
    retries: 3
    interval: 20
    timeout: 180

