# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: fuel-stackurity-theme-deployment-puppet
  type: puppet
  role: [fuel-stackurity-theme_role]
  version: 2.0.0
  role: [primary-controller, controller]
  requires: [horizon]
  parameters:
    puppet_manifest: "stackurity_setup.pp"
    puppet_modules: "/etc/puppet/modules"
    timeout: 300
